### ISSUE TITLE
pdf417 decoder failing to decode  always

### ISSUE THREAD

**Issue by mobassir94** [sparkfish/pdf417decoder#5]
this is the code i tried : 
```
from pdf417decoder import PDF417Decoder
import matplotlib.pyplot as plt
import cv2
from PIL import Image 
npimg = cv2.imread("/content/bar.png")
image = Image.fromarray(npimg)
plt.imshow(image)
decoder = PDF417Decoder(image)

if (decoder.decode() > 0):
    print('decoding')
    decoded = decoder.barcode_data_index_to_string(0)
else:
  print('could not decode')
  
```
  for this high resolution image : https://i.ibb.co/SypTDfh/bar.png
  
  also cropped the barcode region and tried again,,no luck,always failing to decode(returns nothing)

**Comment by PMLS3** [comment]
Also getting the same error, decoder.decode() is always returing 0... print(type(decoder)) = <class 'pdf417decoder.Decoder.PDF417Decoder'>

print(decoder) = <pdf417decoder.Decoder.PDF417Decoder object at 0x00000252A508DDC0>

**Comment by proofconstruction** [comment]
@PMLS3 Which image(s) of a barcode were you using when you got this error?

@mobassir94 This image has some issues: the original print of that card left small gaps between each row of the barcode, which isn't something I've seen in other PDF417 barcodes. Using a handheld Zebra DS22 barcode scanner, it's quite difficult to complete a scan using the image (cropped or otherwise) you sent. I managed to get this much from the original picture, but this may not be all of the encoded information:
`<pin>91[REDACTED]5</pin><name>ABDUR [REDACTED]</name><DOB>[REDACTED]1983</DOB><FP>FMR 20\P<5v8 Y@&N@'Y+S[@L4UF5M@=iI@>aU?YCTBEHGHX#F@L-o\@LOQRPS6F@SE=@c=Zc"dYhN@kPC@n2r4pQJbY_6@$xYbU]+\HJ@k7@^*a>"@[5F%@APLlG@JA@@4">@[\@S</FP><F>Right Index</F><ds>v&BwtC]'%@FR</ds>Ww E_@D50@-'`

When I run this through `pdf417gen` to produce a PDF417-compliant barcode, and then decode this new barcode with `pdf417decoder`, I get the same string back. I think the combination of the original print alignment and small artifacts produced by scanning are causing the failure to decode.

You could try using [Zebra Flossing](https://github.com/sparkfish/zebra-flossing) to clean up the barcode before trying to decode it.

**Comment by jboarman** [comment]
The barcode is definitely "OK", but we may be encountering too many errors that other decoders are able to recover from.  Cognex is my go-to tool of choice when investigating barcodes.  If it can't read it, it's not a good sign.

Here's a slightly redacted version of what the **Cognex** iOS app produces for that barcode from my phone ... note that non-printable chars are being hex-encoded:

`
<pin>91**[REDACTED]**5</pin><name>ABDUR  **[REDACTED]**</name><DOB>**[REDACTED]**1983</DOB><FP>FMR<0x0>**[REDACTED]**<0xB5>6@<0x92><0x1>$xU<0x80><0x93><0x0><0xD2>Yb<0x80><0xA0><0x0>]<0xB6>+<0x80><0xA1><0x0>H<0x93>J@<0xA3><0x0>k<0xCA>7@<0xA5><0x0>^<0xC5>*<0x80><0xA8><0x0><0x81>>"@<0xAA><0x0>[<0x94>5<0x80><0xAB><0x0><0x8B>F%@<0xB8><0x0><0xDA><0x8C>A<0x80><0xBC><0x0><0xC0><0x87>P@<0xC0><0x0><0xFF> E<0x80><0xC2><0x0><0xA0><0x9A>L<0x80><0xC5><0x0>l<0xC7>G@<0xCB><0x0><0xB2><0xAC>J@<0xCD><0x0><0xF3><0x9B>A<0x80><0xCE><0x0><0x8><0xE6>4<0x80><0xD1><0x1><0x12>">@<0xE2><0x0>[<0xCE>\@<0xEB><0x0><0xAD><0xB6>S<0x0><0x0></FP><F>Right Index</F><ds>v&B<0xC0>w<0xD8><0xFA>t<0x1A>C<0x1>**[REDACTED]**<0x13></ds>
`

Guess of the "XML" format being used:
* `<pin></pin>`
* `<name></name>`
* `<DOB></DOB>`
* `<FP>[FINGER-PRINT?]</FP>`
* `<F>Right Index</F>`
* `<ds>[DIGITAL SIGNATURE?]</ds>`

It's possible that all the NULL and other non-printable chars is causing some issues somewhere in the stack when decoding this barcode.

**Comment by mobassir94** [comment]
iirc, i tried this one : https://github.com/dlenski/python-zxing or some other library(i can't remember the name clearly) and it worked fine,thanks
